# python - numpy와 ndarray 자료형

- 스칼라: 하나의 숫자만으로 이루어진 데이터
- 백터: 여러 숫자가 순서대로 모여있는 것, 일반적으로 일차원 배열을 말함
- 행렬: 2차원 배열을 말함
- 텐서: 3차원 이상의 배열을 말함

Ndarray - 다차원 배열을 지원함

In [1]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [2]:
a = np.ones(2)
print(a)
print(a.dtype)

[1. 1.]
float64


In [3]:
a = np.zeros(2)
print(a)
print(a.dtype)

[0. 0.]
float64


In [5]:
np.ones(2, dtype=np.int64) # 원하는 데이터 유형을 명시적으로 지정

array([1, 1], dtype=int64)

In [51]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [52]:
arr.sort()
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [162]:
print(arr.sort())
arr

None


array([1, 2, 3, 4, 5, 6, 7, 8])

In [164]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [165]:
print(arr.argsort())
arr

[1 0 3 5 2 6 4 7]


array([2, 1, 5, 3, 7, 4, 6, 8])

In [45]:
arr[arr.argsort()]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
# np.arange(start, stop, step)
# np.linspace(start, stop, num) - 중요
print(np.linspace(0, 10, 5))
print(np.linspace(0, 10, num= 5))
print(np.linspace(0, 10, num= 11))


[ 0.   2.5  5.   7.5 10. ]
[ 0.   2.5  5.   7.5 10. ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# arr.ndim 
array_example = np.array([])

# 난수

In [59]:
from numpy import random

print(random.rand()) 
print(random.rand(3))
print(random.rand(2, 3))


0.14564590526650079
[0.34075908 0.88580808 0.1855667 ]
[[0.42468945 0.50434129 0.07460362]
 [0.2341723  0.81761606 0.09875106]]


In [60]:
print(random.rand(1, 2, 3)) # 3차원 배열

[[[0.07338643 0.87660491 0.77430884]
  [0.27220708 0.59927929 0.62116187]]]


In [74]:
from numpy import random

print(random.rand()) 
print(random.rand(size=(2,)))
print(random.rand(2))
print(random.rand((4, 3)))


0.1421849476900542


TypeError: rand() got an unexpected keyword argument 'size'

In [91]:
print(random.randn()) #  정규분포

print(random.randn(2))

print(random.randn(2,3))


0.5849227952638947
[ 0.45128869 -0.18038617]
[[ 0.70572349 -1.01769433  0.35314087]
 [ 1.9974729   1.15257631 -0.34939496]]


In [92]:
print(random.randint(2))
print(random.randint(1,7))
print(random.randint(1, 7, 3))
print(random.randint(1, 7, size=(2,3)))

0
5
[4 1 1]
[[3 4 2]
 [6 3 3]]


In [141]:
from numpy import random

print(sorted(random.choice(range(1, 2), 6)))    # sorted 정렬함수
print(sorted(random.choice(range(1, 46), 6, replace=False)))


[1, 1, 1, 1, 1, 1]
[10, 14, 23, 25, 28, 35]


In [121]:
from numpy import random

print(sorted(random.choice(range(1, 2), 6)))
print(sorted(random.choice(range(1, 7), 6, replace=False)))


[1, 1, 1, 1, 1, 1]
[1, 2, 3, 4, 5, 6]


In [144]:
from numpy import random

print(sorted(random.choice(range(5, 3))))
print(sorted(random.choice(range(5, 3), replace=False), p=[0.1, 0, 0.3, 0.6, 0]))


ValueError: 'a' cannot be empty unless no samples are taken

In [161]:
from numpy import random

print(random.uniform()) # [0, 1) 사이의 균등 분포 
print(random.uniform(4, 6)) # [4~6) 사이의 균등 분포 

0.9922297242873678
4.359379400320782


- bins: 구간 수 (기본 10개)