# 자료형 ndarray
- 다차원 배열 ndarray

In [12]:
import numpy as np

a = np.ndarray(shape=(2,2), dtype=int)
a

array([[-2145733996,   955570819],
       [-1487538619, -1649789108]])

In [13]:
import numpy as np

a = np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [14]:
type(a)

numpy.ndarray

In [15]:
print(a.size)
print(a.ndim)
print(a.dtype)


3
1
int32


In [9]:
import numpy as np

np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [10]:
np.array([1,'py',3.12])

array(['1', 'py', '3.12'], dtype='<U32')

In [11]:
import numpy as np
unicode_array = np.array(['가나다','라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [12]:
lang = np.array(['파이썬', '자바','씨'], dtype=str)
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [13]:
a = np.array((1,2,3), dtype=float)
a

array([1., 2., 3.])

In [14]:
b = np.array((1, 2.5, 3))
b

array([1. , 2.5, 3. ])

In [15]:
import numpy as np

print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [16]:
import numpy as np

print(np.arange(2.0))
print(np.arange(2.0, 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


In [17]:
import numpy as np

a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
np.reshape(a, (2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
np.reshape(a, (3, 5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [20]:
b = np.array([1,2,3,4,5,6]).reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.reshape(b,(2, -1))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [23]:
np.linspace(2.0, 3.0, retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [24]:
print( (3-2) / (50-1) )

0.02040816326530612


In [25]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [26]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True)

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [27]:
print( (3-2) / 50)

0.02


In [28]:
np.linspace(2.0, 3.0, num =5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [29]:
np.linspace(2.0, 3.0, num = 5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [33]:
np.arange(0.1, 0.4, 0.1)

array([0.1, 0.2, 0.3, 0.4])

In [34]:
np.arange(1, 4, 1) / 10.0

array([0.1, 0.2, 0.3])

In [35]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [36]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

In [38]:
import numpy as np

a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [39]:
a.dtype

dtype('float64')

In [40]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [41]:
b = np.zeros((2, 1))
b

array([[0.],
       [0.]])

In [42]:
import numpy as np

np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
import numpy as np

np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [47]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [51]:
a = np.eye(3,4, 1)
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
a = np.eye(3, 4, -1)
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [55]:
import numpy as np

np.full([2,3], 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [56]:
np.full([2, 3], (1, 2, 3))

array([[1, 2, 3],
       [1, 2, 3]])

In [57]:
np.full([3,4], range(4))

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [61]:
np.full([4, 3], fill_value=np.arange(4).reshape(4, 1))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [62]:
import numpy as np

np.empty([2, 2])

array([[0.1, 0.2],
       [0.3, 0.4]])

In [64]:
np.empty([2,3], dtype=int)

array([[ 1595503616,         403,           0],
       [          0,           1, -2147483648]])

In [66]:
import numpy as np

a = np. arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [67]:
np.zeros_like(a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
np.ones_like(a)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [69]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

# 배열연산

In [70]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [71]:
print( a + 2)
print( a - 2)
print( a * 2)
print( a / 2)


[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


In [72]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
b = np.full_like(a, [1, 2, 3])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [74]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [75]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [82]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [77]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [83]:
b +=a
b

array([0.5, 2.5, 4.5, 6.5])

In [84]:
a = np.full((2,3), [1,2,3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [85]:
b = np.full((3,2), [2,1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [86]:
a @ b

array([[12,  6],
       [12,  6]])

In [87]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [88]:
b.dot(a)

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

In [90]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [91]:
a.sum()

46

In [92]:
a.sum(axis=0)

array([16, 30])

In [93]:
a.sum(axis=1)

array([30, 13,  3])

In [96]:
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))

46
[16 30]
[30 13  3]


In [99]:
a = np.array([[3,5,8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [100]:
a.cumsum()

array([ 3,  8, 16, 17, 19, 22])

In [101]:
a.cumsum(axis=0)

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [102]:
a.cumsum(axis=1)

array([[ 3,  8, 16],
       [ 1,  3,  6]])

In [2]:
import numpy as np

a = np.array([1, 4, 9])
np.sqrt

<ufunc 'sqrt'>

In [3]:
np.log(a)

array([0.        , 1.38629436, 2.19722458])

In [4]:
import numpy as np

a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [5]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [6]:
np.add(a,b)

array([ 3,  6, 11])

In [7]:
np.divide(a,b)

array([0.5, 2. , 4.5])

In [8]:
np.power(a, b)

array([ 1, 16, 81])

In [73]:
import numpy as np
np.__version__

'1.26.4'

In [74]:
import numpy as np
a = np.power(np.arange(10),2)
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [75]:
print(a[3])
print(a[-2])

9
64


In [76]:
print(a[1:4])
print(a[-2])

[1 4 9]
64


In [77]:
print(a[1:4])
print(a[-5:-1])

[1 4 9]
[25 36 49 64]


In [78]:
print(a[8:2:-1])
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [79]:
a[::-1]

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0], dtype=int32)

In [80]:
a[::-2]

array([81, 49, 25,  9,  1], dtype=int32)

In [81]:
a[2:5] = -100
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81],
      dtype=int32)

In [82]:
a[2:5] = [-5, -5, -5]
a

array([ 0,  1, -5, -5, -5, 25, 36, 49, 64, 81], dtype=int32)

In [83]:
a[2:5] = [-5, -5]

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [84]:
b = np.array([5] * 10)
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [85]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [86]:
b[::2] = -10
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [87]:
b[::2] = np.arange(5)
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

In [88]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [89]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [90]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [91]:
a[-2, :] # :은 생략해도 무방하다.

array([18, 19, 20, 21, 22, 23])

In [92]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [93]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [94]:
a[:,1]

array([ 1,  7, 13, 19, 25])

In [95]:
a[:, 1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [96]:
a[:, ::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [97]:
a[2, 4]

16

In [98]:
a[2][4]

16

In [99]:
a[1:3, 2:5]

array([[ 8,  9, 10],
       [14, 15, 16]])

In [100]:
a[:, :]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [101]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

- 3차원 배열과 슬라이싱

In [102]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [103]:
a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [104]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [105]:
a[:,1,1]

array([ 5, 17])

In [106]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [107]:
a[..., 1]   # a[...,1] == a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [108]:
a[1, ..., 1]

array([13, 17, 21])

In [109]:
a[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 배열 형태 수정

In [111]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [112]:
a.ravel() # a의 1차원 모델

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
a = np.arange(1, 7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [115]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [116]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [117]:
np.transpose(a, (0, 1))

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.transpose(a, (1, 0))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [119]:
b = np.arange(1, 13).reshape(3, 2, 2) #(0,1,1) #(k,j,i)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [120]:
b.T #(1,1,0) #(i,j,k)

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [121]:
np.transpose(b, (0, 1, 2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [122]:
np.transpose(b, (2, 1, 0))

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [123]:
np.transpose(b, (0, 2, 1))

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [124]:
c = np.arange(1, 13).reshape(2, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [125]:
c.transpose((1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [126]:
np.transpose(c, (1,2,0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [127]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [139]:
x = np.array([7, 8, 9])
x

array([7, 8, 9])

In [140]:
y = np.swapaxes([x], 0, 1) # 교수님께 질문 **** y = np.swapaxes(x, 0, 1) 시 오류 발생
y

array([[7],
       [8],
       [9]])

In [141]:
y[0,0] = 10
y

array([[10],
       [ 8],
       [ 9]])

In [142]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [134]:
np.swapaxes(x, 0, 2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [143]:
np.transpose(x, (2, 1,0))

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

# 복사와 보기 뷰(view)
- view

In [144]:
org = np.arange(5) 
org

array([0, 1, 2, 3, 4])

In [148]:
v = org.view()
v

array([0, 1, 2, 3, 4])

In [151]:
v[2] = 200
v

array([  0,   1, 200,   3,   4])

In [152]:
org

array([  0,   1, 200,   3,   4])

- copy (복사)

In [153]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [154]:
c = org.copy()
c

array([0, 1, 2, 3, 4])

In [155]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [156]:
org

array([0, 1, 2, 3, 4])

- 배열이 뷰인지 복사본인지 확인하는 방법

In [20]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b = a
b is a # b = a.view 랑 다른점 id 주소가 같다. view의 경우에는 id 주소가 다르다.

True

In [39]:
print(id(a))
print(id(b))

2183156689456
2183156689456


In [40]:
print(a.base)
print(b.base)

None
None


In [41]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [42]:
c = a.copy()
c

array([[100,   2,   3],
       [  4,   5,   6]])

In [43]:
print(id(a))
print(id(c))

2183156689456
2183156552144
