# 브로드캐스팅
- 브로드캐스팅이란 산술을 수행할 수 있도록 모양이 다른 배열의 크기를 일치시키는 직업이다.

In [1]:
from numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])
a + b

array([11, 11, 11])

In [3]:
from numpy import array

a = array([3, 4, 5, 7])
b = array([8, 7, 6])
a * b

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

- 스칼라 또는 단일 값과 배열의 연산

In [4]:
from numpy import array

a = array([3, 4, 5])
a

array([3, 4, 5])

In [5]:
b = 2
b

2

In [6]:
a + b

array([5, 6, 7])

In [7]:
from numpy import array

A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
A + 2

array([[3, 4, 5],
       [3, 4, 5]])

- 2차원 배열의 브로드캐스팅

In [10]:
from numpy import arange

x = arange(1, 10).reshape(3, 3) # 배열 모양 (3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
y = arange(-1, 2) # 배열 모양 (3,) 이다. 중요 !!
y

array([-1,  0,  1])

In [12]:
x * y 

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [13]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [14]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

- 하나의 배열이 1차원으로 다른 배열 행수와 같은 구조의 브로드캐스팅

In [15]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [18]:
x / y

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [19]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

- 행 또는 열이 1인 브로드캐스팅

In [22]:
from numpy import arange
x = arange(1, 4)
x

array([1, 2, 3])

In [24]:
y = arange(1, 4).reshape(3, 1)
y

array([[1],
       [2],
       [3]])

In [25]:
x * y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [26]:
x - y

array([[ 0,  1,  2],
       [-1,  0,  1],
       [-2, -1,  0]])

In [27]:
from numpy import arange

x = arange(0 , 10, 3).reshape(4, 1)
x

array([[0],
       [3],
       [6],
       [9]])

In [28]:
y = arange(1, 3)
y

array([1, 2])

In [29]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [32]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

- 상수 np.newaxis 활용해 두 배열의 브로드캐스팅

In [41]:
from numpy import array
import numpy as np
x = array([0, 10, 20, 30])
x

array([ 0, 10, 20, 30])

In [39]:
a = x[None, :] # 1차원에서 행이 추가되어 2차원으로 증가하였다.
a

array([[ 0, 10, 20, 30]])

In [42]:
a = x[np.newaxis, :] #None을 상수인 no.newaxis로 대체하여도 같은 결과를 얻는다. // import numpy as np <-- np 정의해줄 것
a

array([[ 0, 10, 20, 30]])

In [43]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

In [44]:
from numpy import array

b = array([1, 2, 3]) # 모양 (3,)인 배열
b

array([1, 2, 3])

In [45]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [47]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

<h3> 브로딩캐스팅의 적용 규칙 </h3>

<ul>
<li> 브로드캐스팅의 첫번쨰 규칙은 연산에 참여하는 배열이 동일한 수의 차원을 갖지 않으면 모든 배열이 동일한 수의 차원을 가질 때까지 작은 배열의 모양에 반복적으로 "1"이 추가된다는 것이다.</li>
</p>
<li> 브로드캐스팅의 두번째 규칙은 특정 차원을 따라 1의 크기를 갖는 배열의 크기로 늘어날 수 있다는 것이다.</li>
</p>
<li> "브로드캐스트" 배열에 대해 배열 요소의 값은 그 차원을 따라 그대로 동일하게 확장된다고 가정한다.</li>


# 고급 색인
- 배열 색인

In [52]:
from numpy import arange
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [55]:
print(x[[2]]) # 표준 파이썬의 리스트와는 다르게 ndarray의 배열은 여러 원소의 인덱싱이 가능하다.
print(x[[2, 3]])

[2]
[2 3]


- 인덱스(Index): 시퀀스 자료형에서 각 요소의 위치를 나타내는 숫자(0부터 시작).
- 인덱싱(Indexing): 인덱스를 사용하여 시퀀스의 특정 요소에 접근하는 방법.
- 음수 인덱싱: 시퀀스의 끝에서부터 요소에 접근 (-1은 마지막 요소).
- 슬라이싱(Slicing): 인덱스 범위를 지정하여 시퀀스의 일부를 추출.

In [56]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [62]:
x[np.array([5, 3, -4, 8])] # 인덱스로는 리스트와 ndarray 배열도 가능하다.

array([5, 3, 6, 8])

In [63]:
x[np.array(10)]

IndexError: index 10 is out of bounds for axis 0 with size 10

- 2차원 배열의 색인

In [64]:
from numpy import arange

x = arange(56).reshape(7, 8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [65]:
x[0, 1] # 일반 색인

1

In [66]:
x[: , 2:8] # 일반 슬라이싱

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [68]:
x[[0], [1]] #고급 색인 // 0축과 1축에 각각 목록이 기술된다.

array([1])

In [71]:
x[: , [5 , 4]] # 모양 (7, 2)의 2차원 배열이 반환됨

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [74]:
x[[1, 3]] # 모양 (2, 8)의 2차원 배열이 반환됨

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [75]:
x[[1, 3], :]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [78]:
x[[1, 3], [2, 2]] # 모양 (2,)인 1차원배열 반환

array([10, 26])

In [79]:
x[[1, 3], 2]

array([10, 26])

In [80]:
x[[1, 3], [3, 3]]

array([11, 27])

In [81]:
x[[1, 3], [3]]

array([11, 27])

In [82]:
from numpy import array

x[array([0, 2, 4]), array([0, 1])] #브로드캐스팅이 될 수 없는 (3,)과 (2,) 모양이면 오류가 발생

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [88]:
x[np.array([0, 2, 4]),1]

array([ 1, 17, 33])

In [90]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


# 다양한 모양의 배열색인
-기본 색인 방법

In [1]:
from numpy import arange

a = arange(40).reshape(5, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [2]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [3]:
a[arange(2, 4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [4]:
a[arange(2, 5)][:, [1, 0, 3, 5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [5]:
a[arange(2, 5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

<h1> 차원 배열 결합과 분리 - chapter 04</h1>

# 배열 결합

- 배열 결합 개요와 기본 함수

- numpy.cstack()

In [1]:
from numpy import arange
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
b = np.arange(6, 12).reshape(3, 2)
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
np.vstack((a, b)) # 두배열을 수직 또는 세로로 쌓아 합쳐놓은 모양 (6, 2) 배열이 됨

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
c = np.arange(20, 24).reshape(2, 2) # 함수 np.vstack(tup)에서 tup은 튜플 자료형으로 합칠 여러 배열이다.
c

array([[20, 21],
       [22, 23]])

In [14]:
np.vstack((a, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [15]:
np.vstack((a, b, c))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [17]:
d = np.array([100, 200]) # 1차원 배열인 d가 확장되어 수직으로 합쳐짐
np.vstack((a, d))

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [19]:
d = np.array([100, 200, 300]) # 1차원 배열이면 길이가 같아야 수직으로 합칠 수 있다.
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

- numpy.hstack()

In [3]:
import numpy as np

a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b = np.arange(10, 19).reshape(3, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
np.hstack((a, b)) # 수평으로 합침

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [6]:
c = np.array([[10, 20], [30, 40]])
c

array([[10, 20],
       [30, 40]])

In [7]:
np.hstack((a, c))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [29]:
np.hstack((np.arange(3), np.arange(10, 15)))

array([ 0,  1,  2, 10, 11, 12, 13, 14])

- 배열 결합 연산 column_stack()과 row_stack()

In [11]:
import numpy as np
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [12]:
b = np.arange(10, 22).reshape(3, 4)
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [13]:
np.column_stack((a, b))

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [16]:
np.hstack((a, b)) # 2차원 배열에서 np.hstack과 np.column_stack이 같다.

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [18]:
x = np.array([1, 2, 3]) # 1차원 배열을 축 1 로 확장한 이후, 열로 쌓아 만든 2차원 배열을 반환한다.
y = np.array([10, 20, 30])
np.column_stack((x, y))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [20]:
x[:, np.newaxis] #1차원 배열에서 두번째 축인 1축을 증가시키는 것은 이와 같은 코드로 가능하다.

array([[1],
       [2],
       [3]])

In [23]:
y[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [24]:
x = np.array([1 ,2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis],y[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [25]:
# 이는 colum_stack이 hstack과 다른 점을 보여준다.
np.hstack((x, y))

array([ 1,  2,  3, 10, 20, 30])

In [26]:
np.column_stack == np.hstack

False

- numpy.row_stack()

In [27]:
import numpy as np

a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
b = np.arange(10 ,22).reshape(4, 3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [29]:
np.row_stack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [30]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [32]:
a = np.array([4., 2., 1.])
b = np.array([3. , 8., 7.])
print(np.row_stack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [33]:
print(np.vstack((a, b)))

[[4. 2. 1.]
 [3. 8. 7.]]


In [35]:
np.row_stack == np.vstack # row_stack과 vstack은 서로 같다.

True

# 배열 결합 연산 numpy.concatenate()와 stack()
- numpy.concatenate()

In [36]:
import numpy as np 

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [38]:
np.concatenate((a, b, c), axis=None) # np.concatenate()는 축 0을 중심으로 합치는 역할을 한다.

array([1, 2, 3, 4, 5, 6])

In [42]:
np.concatenate((a, b, c), axis = 0)

array([1, 2, 3, 4, 5, 6])

In [43]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [45]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [46]:
np.concatenate((x, y))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [47]:
np.concatenate((x, y, z))

TypeError: only integer scalar arrays can be converted to a scalar index

In [48]:
np.concatenate((x, y), axis =1)

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [49]:
np.concatenate((x, y ,z), axis = 1)

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [50]:
np.concatenate((x, y), axis=None)

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

- numpy.stack()

In [53]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [58]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [59]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
np.stack((a, b), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
np.stack((a, b), axis=-1) # -1은 마지막 축을 의미한다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [69]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [70]:
ax0 = np.stack((x, y, z), axis=0)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [71]:
ax0.shape

(3, 2, 3)

In [72]:
ax1 = np.stack((x, y, z), axis=1)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [73]:
ax2 = np.stack((x, y, z), axis=2)
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [74]:
ax0.shape

(3, 2, 3)

In [76]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
x[:, :, np.newaxis]

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [79]:
np.expand_dims(x, axis=2) # np.expand_dims() 으로도 축을 늘릴 수 있다.

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [80]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [81]:
y[:, :, np.newaxis]

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [82]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [83]:
np.expand_dims(z, axis=2)

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [84]:
np.stack((x, y, z), axis=2)

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

# 배열의 결합 비교
- column_stack(과 hstack()

In [89]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
c =np.arange(1, 6, 2)
c

array([1, 3, 5])

In [91]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [92]:
np.hstack((a, c[:, np.newaxis]))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [93]:
np.hstack((a, c))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [94]:
np.hstack((a, np.expand_dims(c, axis=1)))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [95]:
np.column_stack((a, c)) # column_stack은 축을 늘릴 필요없이 바로 합칠 수 있다.

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

row_stack()과 vstack()

In [96]:
import numpy as np
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [98]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [99]:
np.row_stack((a, b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [100]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

- np._c[]와 np.column_stakc()

In [102]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5 , 6])

In [130]:
np.c_[a, b] # np.c_은 np.column_stack과 유사하게 1차원 배열을 1축으로 늘려 수평으로 합친 결과를 반환한다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [131]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [132]:
np.column_stack == np.c_ # np.c_ 와 np.column_stack이 서로 같진 않음

False

In [133]:
x = np.array([[1, 2, 3]]) # 2차원 배열
y = np.array([[4, 5, 6]])

In [134]:
np.c_[x, y] # 수평으로 연결

array([[1, 2, 3, 4, 5, 6]])

In [135]:
np.column_stack((x, y))  # 수평으로 연결

array([[1, 2, 3, 4, 5, 6]])

In [136]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [139]:
np.column_stack([x, 10, 20, y])

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

# np.r_[]
- np.r_[]

In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

In [2]:
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [3]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [6]:
np.r_[1, 0, 0, b]

array([1, 0, 0, 4, 5, 6])

In [7]:
np.r_[3:10:3, [0]*2, 5, 6]

array([3, 6, 9, 0, 0, 5, 6])

In [19]:
np.r_[-1:1:6j, [0]*2, 5, 6]

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [20]:
np.linspace(-1, 1, 6)

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

- np.r_['i, j, k', a, b]

In [21]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
np.r_[a, a, a] # concatenate along first axis

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [23]:
np.r_['0', a, a]

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [24]:
np.r_['-1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [25]:
np.r_['1', a, a]

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [26]:
np.r_['0,2',[1,2,3], [4, 5, 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.r_['0, 3', [1, 2, 3], [4, 5, 6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [28]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]]

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [29]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape

(6, 1, 1)

In [32]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [34]:
np.r_['0, 3, 1', [1,2,3], [4,5,6]].shape

(2, 3, 1)

In [35]:
np.r_['0, 3, 2', [1,2,3], [4,5,6]]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

# 1차원 배열, 벡터의 다양한 결합 방법
- 여러 1차원 배열울 수평 방향으로 합치는 방법

In [36]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [37]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [38]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [39]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

In [41]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :]))

array([[1, 2, 3],
       [4, 5, 6]])

- 여러 1차원 배열을 행으로 솩장해 수평 방향으로 합치는 방법

In [45]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])
             
print(a.shape)
print(b.shape)

(3,)
(3,)


In [48]:
np.column_stack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis]))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [52]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])